<a href="https://colab.research.google.com/github/hida0/ESAA/blob/main/Week1(Fri)_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#개념정리 & 개념필사
##[넘파이 **Numpy**]
*   **Numerical Python**의 줄임말로 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지이다. 루프를 사용하지 않고 대량 데이터의 배열 연산을 가능하게 하여 빠른 배열 연산 속도를 보장하고 다양한 데이터 핸들링 기능을 제공한다.
*   관례적으로 numpy를 import 할때, 약어인 np를 사용한다.

In [1]:
import numpy as np

##[넘파이 **ndarray**]
*  넘파이의 기본 데이터 타입으로 다차원 배열을 쉽게 생성하고 다양한 연산이 가능하다.
* **array()** 함수에 변환을 원하는 객체를 리스트 등의 인자로 입력하면 ndarray를 반환한다.
* **shape** 변수를 이용하면 생성된 ndarray의 차원과 크기를 튜플 형태로 나타낸다.

In [2]:
array2 = np.array([[1,2,3],
                   [4,5,6]])
print("array2:\n", array2)
print("array2 type:", type(array2))
print("array2 array 형태:", array2.shape)

array2:
 [[1 2 3]
 [4 5 6]]
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


## [ndarray의 데이터 타입]
*   ndarray 내의 데이터값은 숫자(int, float 등), 문자열, 불 값 등 모두 가능하지만 연산의 특성상 **같은 데이터 타입만 가능**하다.
*  **dtype** 을 통해 데이터 타입을 확인할 수 있다.
*  **astype()** 메서드를 이용하여 ndarray 내 데이터값의 타입을 변경할 수 있다.

In [3]:
#같은 데이터 타입의 ndarray 변환
list1 = [1,2,3]
array1 = np.array(list1)
print(type(list1), type(array1))
print(array1, array1.dtype)

<class 'list'> <class 'numpy.ndarray'>
[1 2 3] int64


In [4]:
#int형과 string형 혼합 데이터 타입의 ndarray 변환 -> 모두 string형
list2 = [1,2,'test']
array2 = np.array(list2)
print(type(list2), type(array2))
print(array2, array2.dtype)

<class 'list'> <class 'numpy.ndarray'>
['1' '2' 'test'] <U21


In [5]:
#int형과 float형 혼합 데이터 타입의 ndarray 변환 -> 모두 float형
list3 = [1,2,3.0]
array3 = np.array(list3)
print(type(list3), type(array3))
print(array3, array3.dtype)

<class 'list'> <class 'numpy.ndarray'>
[1. 2. 3.] float64


## [ndarray를 편리하게 생성하기]
#### **arange()**
*  파이썬 표준함수인 range()와 유사한 기능을 한다.
*  **0부터 함수의 인자 값-1**까지 순차적으로 증가하는 데이터값을 가지는 1차원 ndarray를 만든다.
*  default 함수 인자는 stop 값이며, start 값도 부여하여 0이 아닌 다른 값부터 시작한 연속 값을 부여할 수도 있다.

#### **zeros()**
* 함수의 인자로 튜플 형태의 shape 값을 입력하면 모든 값이 0이고, 해당 shape을 가진 ndarray를 반환한다.
* dtype으로 데이터타입을 지정할 수 있으며, 지정하지 않으면 defalut값은 float64형이다.

#### **ones()**
* 함수의 인자로 튜플 형태의 shape 값을 입력하면 모든 값이 1이고, 해당 shape을 가진 ndarray를 반환한다.
* dtype으로 데이터타입을 지정할 수 있으며, 지정하지 않으면 defalut값은 float64형이다.



In [6]:
#stop값만 지정한 1차원 ndarray
seq_array = np.arange(10)
print(seq_array)
print(seq_array.dtype, seq_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [7]:
#데이터타입을 int형으로 지정한 모든 값이 0인 ndarray
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

#데이터타입을 지정하지 않은 모든 값이 1인 ndarray -> float형
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


##[ndarray의 차원과 크기를 변경하는 **reshape()**]
* **reshape()** 메서드에 변환을 원하는 크기를 함수 인자로 부여하면 ndarray를 특정 차원 및 크기로 변환할 수 있다.
* 지정된 사이즈로 변경이 불가능하면 오류가 발생한다.
* 인자로 **-1**를 사용하면 지정한 다른 인자와 함께 원래 ndarray에 호환 가능한 새로운 shape으로 변환한다.
* **reshape(-1,1)**와 같은 형태로 자주 사용하여 원본 ndarray가 어떤 형태라도 2차원이고 여러 개의 row를 가지지만 반드시 1개의 column을 갖는 ndarray로 변환한다.



In [8]:
#1차원 (10,)의 ndarray
arr1 = np.arange(10)
print('arr1:', arr1)

#2차원 (2,5)의 ndarray
arr2 = arr1.reshape(2,5)
print('arr2:\n', arr2)

#2차원 (5,2)의 ndarray
arr3 = arr1.reshape(5,2)
print('arr3:\n', arr3)

arr1: [0 1 2 3 4 5 6 7 8 9]
arr2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [9]:
#1차원 (10,)의 ndarray
arr1 = np.arange(10)
print('arr1:', arr1)

#2차원 (-1,5)의 ndarray
arr2 = arr1.reshape(-1,5)
print('arr2:', arr2.shape, '\n', arr2)

#2차원 (5,-1)의 ndarray
arr3 = arr1.reshape(5,-1)
print('arr3:', arr3.shape, '\n', arr3)

arr1: [0 1 2 3 4 5 6 7 8 9]
arr2: (2, 5) 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr3: (5, 2) 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## [넘파이의 ndarray의 데이터 세트 선택하기 - **인덱싱(Indexing)**]
#### 1. **특정한 데이터**만 추출
* 1차원 데이터에서 단일 값을 추출하려면 ndarray 객체에 해당하는 위치의 인덱스 값을 [ ] 안에 입력한다.
* 단일 인덱스를 이용하여 ndarray 내의 데이터값을 간단하게 수정할 수 있다.
* 2차원 데이터에서 단일 값을 추출하려면 콤마(,)로 분리하여 [ , ] 안에 row와 column 위치를 입력한다.
* 다차원 ndarray에서 **axis 0은 row 방향 축, axis 1은 column 방향 축, axis 2는 높이 방향 축**이다.

#### 2. **슬라이싱(Slicing)**
* **' : '** 기호를 이용하여 **시작 인덱스부터 종료 인덱스-1**의 위치까지 연속한 데이터를 슬라이싱해서 추출한다.
* 슬라이싱 기호인 ' : ' 사이의 시작과 종료 인덱스는 생략이 가능하며, 생략하면 자동으로 맨 처음/맨 마지막으로 간주한다.
* 추출된 데이터 세트는 ndarray 타입이다.

#### 3. **팬시 인덱싱(Fancy Indexing)**
* 일정한 **인덱싱 집합을 리스트나 ndarray 형태로 지**정하여 해당 위치의 인덱스에 해당하는 데이터의 ndarray를 반환한다.
* 추출된 데이터 세트는 ndarray 타입이다.

#### 4. **불린 인덱싱(Boolean Indexing)**
* **특정 조건에 해당하는지에 대한 여부인 True/False 값** 인덱싱 집합을 기준으로 **True에 해당**하는 인덱스 위치에 있는 데이터의 ndarray를 반환한다.
* ndarray의 인덱스를 지정하는 [ ] 내에 조건문을 그대로 기재한다.
* 조건 필터링과 검색을 동시에 할 수 있기 때문에 자주 사용되는 방식이다.
* 추출된 데이터 세트는 ndarray 타입이다.



In [10]:
#슬라이싱
arr1d = np.arange(1,10)
arr2d = arr1d.reshape(3,3)
print("arr2d:\n", arr2d)

print("arr2d[0:2, 0:2]\n", arr2d[0:2, 0:2])
print("arr2d[1:3, :]\n", arr2d[1:3, :])
print("arr2d[:2, 1:]\n", arr2d[:2, 1:])

arr2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[0:2, 0:2]
 [[1 2]
 [4 5]]
arr2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
arr2d[:2, 1:]
 [[2 3]
 [5 6]]


In [11]:
#불린 인덱싱
arr1d = np.arange(1,10)
print("arr1d:", arr1d)
print("arr1d > 5:", arr1d > 5)
arr2 = arr1d[arr1d > 5]
print("arr1d > 5 불린 인덱싱 결과 값:", arr2)

arr1d: [1 2 3 4 5 6 7 8 9]
arr1d > 5: [False False False False False  True  True  True  True]
arr1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


## [행렬의 정렬 - **sort()** 와 **argsort()**]
#### **sort()** : 행렬을 정렬한다.
* **np.sort()** : 넘파이에서 sort()를 호출하는 방식으로 **원 행렬은 그대로 유지**한 채로 정렬된 행렬을 반환한다. 
* **ndarray.sort()** : **원 행렬 자체를 정렬한 형태로 변환**하며 반환하는 값은 None이다.
* 내림차순으로 정렬하기 위해서는 **[::-1]** 을 적용한다.
* 행렬이 2차원 이상일 경우에는 axis 축의 값을 설정하여 **row 방향(axis=0)** 또는 **column 방향(axi=1)**으로 정렬할 수 있다.

#### **argsort()** : 원본 행렬이 정렬되었을 때, 정렬된 행렬의 원본 행렬 인덱스를 추출한다.
* np.argsort() 는 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환한다.
* 내림차순으로 정렬하기 위해서는 **[::-1]** 을 적용한다.




In [12]:
#np.sort()를 이용
org_array = np.array([3,1,9,5])
sort_array1 = np.sort(org_array)[::-1]
print("원본 행렬:", org_array)
print("np.sort() 호출 후 반환된 정렬 행렬:", sort_array1)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [9 5 3 1]


In [13]:
#ndarray.sort()를 이용
org_array = np.array([3,1,9,5])
sort_array2 = org_array.sort()
print("org_array.sort() 호출 후 반환된 정렬 행렬:", sort_array2)
print("org_array.sort() 호출 후 원본 행렬:", org_array)

org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [14]:
array2d = np.array([[8,12],
                    [7,1]])
print("array2d:\n", array2d)

#row 방향으로 정렬
sort_array2d_axis0 = np.sort(array2d, axis=0)
print("row 방향으로 정렬:\n", sort_array2d_axis0)

#column 방향으로 정렬
sort_array2d_axis1 = np.sort(array2d, axis=1)
print("column 방향으로 정렬:\n", sort_array2d_axis1)

array2d:
 [[ 8 12]
 [ 7  1]]
row 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
column 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [15]:
org_array = np.array([3,1,9,5])
sort_array = np.sort(org_array)
sort_indices = np.argsort(org_array)
print("np.sort() 호출 후 정렬된 행렬:", sort_array)
print("행렬 정렬 시 원본 행렬의 인덱스:", sort_indices)
print(type(sort_indices))

sort_array2 = np.sort(org_array)[::-1]
sort_indices2 = np.argsort(org_array)[::-1]
print("np.sort() 호출 후 내림차순으로 정렬된 행렬:", sort_array2)
print("행렬 내림차순 정렬 시 원본 행렬의 인덱스:", sort_indices2)

np.sort() 호출 후 정렬된 행렬: [1 3 5 9]
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
<class 'numpy.ndarray'>
np.sort() 호출 후 내림차순으로 정렬된 행렬: [9 5 3 1]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


## [선형대수 연산 - 행렬 내적과 전치 행렬 구하기]
#### 행렬 내적(행렬 곱) : **np.dot()**
* 두 행렬 A와 B의 내적은 np.dot()을 이용해 계산한다.
* 왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야만 내적 연산이 가능하다.

#### 전치 행렬 : **np.transpose()**
* 원 행렬에서 행과 열의 위치를 교환한 원소로 구성한 행렬을 그 행렬의 전치 행렬이라고 한다.

In [16]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
print("A.shape:", A.shape, "*", "B.shape:", B.shape, "=> (2, 2)")
dot_product = np.dot(A,B)
print("행렬 내적 결과:\n", dot_product)

A.shape: (2, 3) * B.shape: (3, 2) => (2, 2)
행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [17]:
A = np.array([[1,2],
              [3,4]])
A_trans = np.transpose(A)
print("원본 행렬 A:\n", A)
print("A의 전치 행렬:\n", A_trans)

원본 행렬 A:
 [[1 2]
 [3 4]]
A의 전치 행렬:
 [[1 3]
 [2 4]]
