# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
x = np.arange("2016-07", "2016-08", dtype="datetime64[D]")
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3) * 1
B = np.ones(3) * 2
np.add(A, B, out=B)
print(B)
np.divide(A, 2, out=A)
print(A)
np.negative(A, out=A)
print(A)
np.multiply(A, B, out=A)
print(A)

[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
x = np.random.uniform(0,10,10)
print(x) 
print(x - x%1) #x에서 x를 1로 나눈 나머지를 빼서 정수부분을 구함
print(np.floor(x)) #np.floor를 이용하여 내림
print(np.ceil(x))  #np.ceil을 이용하여 올림
print(x.astype(int)) #astype을 이용하여 integer로 변환
print(np.trunc(x)) #input의 소숫자리를 자른 후의 value를 나타냄

[9.6972659  8.84041105 5.37429598 4.35899971 8.53119299 9.73253764
 4.99706666 2.50794972 1.83265709 4.78485564]
[9. 8. 5. 4. 8. 9. 4. 2. 1. 4.]
[9. 8. 5. 4. 8. 9. 4. 2. 1. 4.]
[10.  9.  6.  5.  9. 10.  5.  3.  2.  5.]
[9 8 5 4 8 9 4 2 1 4]
[9. 8. 5. 4. 8. 9. 4. 2. 1. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
x = np.zeros((5,5))
y = np.arange(5)
print(x+y)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generator():
    for i in range(10):
        yield i  #return이 아닌 yield를 사용한다. return을 할 경우 처음 값만 도출되지만 yield는 값을 내보낼 수도 넣어줄 수도 있다.
x = np.fromiter(generator(),dtype="float",count=-1) #np.fromiter를 통해 표현가능한 객체로부터 새로운 1차원 array를 만든다.
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
x = np.linspace(0,1,11,endpoint=False) #np.linspace(시작(포함),끝(포함),갯수)
x = x[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
x = np.random.random(10)
x.sort()
print(x)

[0.04973337 0.16265045 0.27313295 0.30683352 0.32550302 0.32898714
 0.52258359 0.78542977 0.84844109 0.94619697]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
x = np.random.random(10)
np.add.reduce(x)

7.002473404105704

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print("A:", A, "B:", B)
print(np.allclose(A,B))
print(np.array_equal(A,B))

A: [0 0 0 1 1] B: [1 0 1 0 0]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
x = np.zeros(10)
x.flags.writeable = False #x.flags.writeable = False로 설정함으로써 변수를 변경하는 것을 막는다.
x[0]= 1

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2) #Cartesian coordinates √X^2+Y^2
P = np.arctan2(Y,X) #극좌표계(polar)를 나타내기 위해 arctan2를 사용
print(R)
print(P)

[0.18469896 0.4752382  0.68061064 0.08582791 1.18816895 0.88061916
 0.94197267 0.72728582 0.42315598 1.15359662]
[0.10211421 0.73963912 1.23250734 1.22110812 0.79476585 0.49101904
 0.13577378 1.19127405 1.47383537 1.00804915]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
x = np.random.random(10)
print(x)
print(x.argmax()) #최댓값의 인덱스를 찾는다.
x[x.argmax()]=0
print(x)

[0.7090105  0.02985458 0.2045606  0.49366537 0.98906039 0.68043573
 0.1355891  0.07157644 0.0850051  0.42853325]
4
[0.7090105  0.02985458 0.2045606  0.49366537 0.         0.68043573
 0.1355891  0.07157644 0.0850051  0.42853325]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
Z = np.zeros((5,5),[('x',float),('y',float)]) #(x,y) 좌표값 쌍 즉, 그리드 포인트(grid point)를 생성하여 각 좌표에 대한 함수 값을 계산해야 한다.
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,2,5)) 
#Meshgrid를 통해 사각형 영역을 구성하는 가로축의 점들과 세로축의 점을 나타내는 두 벡터를 인수로 받아서 이 사각형 영역을 이루는 조합을 출력한다.
print(Z)

[[(0.  , 0. ) (0.25, 0. ) (0.5 , 0. ) (0.75, 0. ) (1.  , 0. )]
 [(0.  , 0.5) (0.25, 0.5) (0.5 , 0.5) (0.75, 0.5) (1.  , 0.5)]
 [(0.  , 1. ) (0.25, 1. ) (0.5 , 1. ) (0.75, 1. ) (1.  , 1. )]
 [(0.  , 1.5) (0.25, 1.5) (0.5 , 1.5) (0.75, 1.5) (1.  , 1.5)]
 [(0.  , 2. ) (0.25, 2. ) (0.5 , 2. ) (0.75, 2. ) (1.  , 2. )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
x = np.arange(5)
y = x + 0.5   
print("x:", x, "y:", y) 
print(np.subtract(x, y)) #x-y
C = 1.0 / np.subtract.outer(x, y) #각각의 i,j에 해당하는 성분을 추출하여 뺀 값으로 행렬 생성
print(C)

x: [0 1 2 3 4] y: [0.5 1.5 2.5 3.5 4.5]
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4       ]
 [ 0.4         0.66666667  2.         -2.         -0.66666667]
 [ 0.28571429  0.4         0.66666667  2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min) #iinfo()는 int에 대한 정보
    print(np.iinfo(dtype).max)
print("-----------------")
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min) #finfo()는 float에 대한 정보
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps) #eps는 표현가능한 가장 작은 값

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-----------------
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
x = np.zeros((16,16))
np.set_printoptions(threshold=np.inf) #자료의 개수가 많아도 중간에 생략하지 않고 모두 보여주도록 한다.
x

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
x = np.arange(100)
y = np.random.uniform(0, 100)
print(y)
print(np.abs(x-y).min()) #x에서 y를 뺀 값에 절댓값을 취한 것 중에 가장 작은 값, 이 값이 작을수록 y와 비슷하다.
index = (np.abs(x-y)).argmin() #x-y에 절댓값을 취한 값 중에 최솟값(=y와 가장 가까운 값)의 인덱스
print(x[index])

37.52375142666637
0.4762485733336277
38


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
x = np.zeros(10,[('position',[('x',float,1),
                             ('y',float,1)]),
                ('color', [('r',float,1),
                          ('g',float,1),
                          ('b',float,1)])])
x

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
Z = np.random.random((10,2))
x, y = np.atleast_2d(Z[:,0],Z[:,1]) #np.atleat_2d : View inputs as arrays with at least two dimensions.
D = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(D)

[[0.         0.69679158 0.82190908 0.60271328 0.47175232 0.28045892
  0.34072475 0.47308968 0.48288656 0.79522883]
 [0.69679158 0.         0.17942421 0.10206039 0.89903392 0.81485614
  0.6942044  1.00253989 1.13403858 0.75115308]
 [0.82190908 0.17942421 0.         0.23223839 0.94063346 0.89149123
  0.86270228 1.06088956 1.22310665 0.68740247]
 [0.60271328 0.10206039 0.23223839 0.         0.79876056 0.71284637
  0.63267206 0.90073193 1.03303851 0.68333542]
 [0.47175232 0.89903392 0.94063346 0.79876056 0.         0.1950829
  0.81145169 0.14689461 0.39374361 0.51933727]
 [0.28045892 0.81485614 0.89149123 0.71284637 0.1950829  0.
  0.62118277 0.20680618 0.33568423 0.62799253]
 [0.34072475 0.6942044  0.86270228 0.63267206 0.81145169 0.62118277
  0.         0.80943596 0.76841111 1.06513115]
 [0.47308968 1.00253989 1.06088956 0.90073193 0.14689461 0.20680618
  0.80943596 0.         0.25414892 0.66506336]
 [0.48288656 1.13403858 1.22310665 1.03303851 0.39374361 0.33568423
  0.76841111 0.254148

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
x = np.arange(10, dtype=np.float32)
x = x.astype(np.int32, copy=False) #copy=False : 복사 대신에 반환한다.
print(x.dtype)

int32


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")

x = np.genfromtxt(s, delimiter=",",dtype=np.int) #텍스트파일에서 데이터를 로드한다. 결측값은 지정된 대로 처리된다.
print(x)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
x = np.arange(9).reshape(3,3)
print(x)
for index, value in np.ndenumerate(x): #np.ndenumerate: 다차원 인덱스 반환
    print(index, value)
print("---------")
for index in np.ndindex(x.shape): #np.ndindex: 인덱스 배열에 대한 N차원 반복 개체
    print(index, x[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
---------
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
x, y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
D = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 5
p = 3
x = np.zeros((n,n))
y = np.random.choice(range(n*n), p, replace=False)
np.put(x, y, 1) #np.put: 배열의 지정된 요소를 지정된 값으로 바꾼다.
                                                             #np.random.choice: 지정된 배열 내에서 지정된 길이의 1차원 배열 랜덤 표본을 생성한다.
print(y)
print(x)

[ 1 21  8]
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
x = np.random.rand(3, 5)
y = x - x.mean(axis=1,keepdims=True)  #axis=1은 행선택 , keepdims로 차원 유지
print(y)

[[ 0.00165176 -0.25117933 -0.0933145  -0.28452985  0.62737192]
 [ 0.42360257  0.16864607 -0.12248596 -0.21131888 -0.2584438 ]
 [-0.44445672  0.24731189 -0.07282728 -0.00886286  0.27883497]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
x = np.random.randint(0, 10, (3,3))
print(x)
print("----------")
print(x[x[:,1].argsort()])
#각 행의 2열 성분의 크기의 내림차순으로 정렬한다. ( 9, 3, 6 -> 3, 6, 9 ) 

[[3 9 2]
 [7 3 6]
 [8 6 2]]
----------
[[7 3 6]
 [8 6 2]
 [3 9 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
x = np.random.randint(0, 3, (3, 5))
print(x)
print((~x.any(axis=0)).any())
#열의 성분이 전부 0인 null column이 있는지

[[1 1 2 0 0]
 [2 2 0 0 2]
 [0 0 0 0 2]]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
x = np.random.uniform(0,1,10)
z = 0.5 
print(x)
index = np.abs(x-z).argmin() #x-z의 절댓값이 가장 작은 값의 인덱스
print(x[index]) #x-z의 절댓값이 가장 작은 값

[0.25664975 0.67354247 0.55381736 0.35226093 0.7264629  0.83265964
 0.53991595 0.5649871  0.75046805 0.22812993]
0.539915953559757


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
it = np.nditer([A, B, None]) #np.nditer: for문을 사용하지 않고 다차원 배열을 순회하게 하는 함수
for x,y,z in it: 
    z[...] = x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
x = np.ones(10)
a = np.random.randint(0,len(x),20)
np.add.at(x, a, 1) #a의 값에 해당하는 x의 인덱스에 1씩 더함 -> a의 첫째항이 0이라면 x의 첫째항에 +1
print(a)
print(x)

[0 0 8 0 3 7 5 1 0 9 3 0 0 8 2 8 8 2 9 7]
[7. 2. 3. 3. 1. 2. 1. 3. 5. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [3,4,5,6,7,8]
F = np.bincount(I, X) #I에 X의 값들이 몇번 나오는지를 센다. 개수 측정의 범위는 0부터 X의 최댓값까지
print(F)

[0. 0. 0. 1. 2. 3. 4. 5. 6.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
img = np.random.randint(0,2,(16,16,3)).astype(np.ubyte)
F = img[...,0]*(256*256) + img[...,1]*256 + img[...,2]
print(len(np.unique(F)))

8
